server:
  port: 8081

spring:
  datasource:
    # tidb
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.25.201.147:4000/JDEDB?characterEncoding=utf8
    username: root
    password: d24EWPDj4j

  main:
    allow-bean-definition-overriding: true

#jdbc
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:mysql://127.0.0.1:3306/test?
#  username: root
#  password: 111111
#  # 最大连接数
#  maxCount: 20