server:
  port: 8080

spring:
  datasource:
    # tidb
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.25.201.147:4000/JDEDB?characterEncoding=utf8
#    username: root
#    password: d24EWPDj4j

#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://frps.elitescloud.com:25142/jyj_fc?rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: 123456

  main:
    allow-bean-definition-overriding: true

#jdbc
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:mysql://127.0.0.1:3306/test?
#  username: root
#  password: 111111
#  # 最大连接数
#  maxCount: 20